version: 2

project_name: shinkro
before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/shinkro/
    binary: shinkro
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: darwin
        goarch: arm
      - goos: freebsd
        goarch: arm
      - goos: freebsd
        goarch: arm64

archives:
  - name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: "New Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: Other work
      order: 999

release:
  prerelease: auto
  footer: |
    **Full Changelog**: https://github.com/varoOP/shinkro/compare/{{ .PreviousTag }}...{{ .Tag }}

    ## Docker images
    
    - `docker pull ghcr.io/varoOP/shinkro:{{ .Tag }}`
    
    ## What to do next?
    
    - Read the [documentation](https://docs.shinkro.com)
    - Join our [Discord server](https://discord.gg/ZkYdfNgbAT)
