---
version: "1.0"
services:
  shinkro:
    image: shinkro:dev
    container_name: shinkro
    volumes:
      - ./config:/config
    ports:
      - "7011:7011"
    restart: unless-stopped
    environment:
      #Required for first start
      - SHINKRO_USERNAME=shinkro
      - SHINKRO_PASSWORD=shinkro
      - PLEX_USERNAME=shinkro
      - ANIME_LIBRARIES=Library1,Library2,Library3
      #Optional
      #- PUID=1000
      #- PGID=1000
